package it.innove;

public enum BleErrorCode {
    NOT_SUPPORTED(1),
    NO_BLUETOOTH_SUPPORT(2),
    USER_REFUSED_ENABLE(4),
    CURRENT_ACTIVITY_UNAVAILABLE(6),
    INVALID_PERIPHERAL_UUID(8),
    MAX_BOND_REQUESTS_REACHED(10),
    CREATE_BOND_FAILED(12),
    REMOVE_BOND_FAILED(14),
    PERIPHERAL_NOT_FOUND(16),
    SERVICE_UUID_OR_CHARACTERISTIC_UUID_MISSING(18),
    BOND_REQUEST_DENIED(20),
    ILLEGAL_REMOVE_WHILE_CONNECTED(22),
    WRITE_DESCRIPTOR_FAILED(24),
    MISSING_NOTIFY_OR_INDICATE_FLAG(26),
    SET_NOTIFICATION_FAILED(28),
    CHARACTERISTIC_NOT_FOUND(30),
    PERIPHERAL_NOT_CONNECTED(32),
    GATT_IS_NULL(34),
    PERIPHERAL_DISCONNECTED(36),
    CONNECTION_ERROR(38),
    INVALID_ADK_VERSION(40),
    READ_FAILED(42),
    RSSI_READ_FAILED(44),
    CACHE_REFRESH_FAILED(46),
    UNKNOWN_EXCEPTION(48),
    WRITE_FAILED(50),
    WRITE_INTERRUPTED(52),
    IOS_ERROR(53),
    ANDROID_ERROR(54),
    ATT_ERROR(55);

    private int numVal;

   BleErrorCode(int numVal) {
        this.numVal = numVal;
    }

    public int getNumVal() {
        return numVal;
    }
}
